language: ruby
cache: bundler
sudo: false

before_install:
  - gem install bundler
  - bundle --version
  - gem update --system
  - gem --version

branches:
  only:
    - master

bundler_args: --jobs 7 --retry 3

matrix:
  include:
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.10.9'\""
      rvm: 2.5.3
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.9.13'\""
      rvm: 2.5.3
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.8.12'\""
      rvm: 2.5.3
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.7.17'\""
      rvm: 2.5.3
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.6.47'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.5.33'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.4.56'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.3.37'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.2.0'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.1.12'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 14.0.202'\""
      rvm: 2.5.1
    - env: "GEMFILE_MOD=\"gem 'chef', '= 13.12.14'\""
      rvm: 2.4.5
